### ISSUE TITLE
initialLayout is not defined

### ISSUE THREAD

**Issue by bernardinosousa** [Qwiko/nextbox-ui-plugin#13]
Installed via git repository, using Netbox v3.3.8

**Comment by Qwiko** [comment]
Hi, sorry for the late response.
Can you give me more information about this error?
Where are you getting it? Do you have a screenshot?

**Comment by mhabiballa** [comment]
Ok, I'll jump in instead. For my deployment, there is no overall topology shown. There are separate devices shown per sites (not connected not all devices).
Another question, how to find the default img directory of nextbox where default imgs are used? Also, I'm really confused about ('layers_sort_order' vs 'icon_model_map' vs 'icon_model_map' vs 'icon_model_map')

**Comment by Qwiko** [comment]
@mhabiballa 
You have to perform a search to get a Topology view. There is no global view without any search.

For the other error, in the netbox application.log you should get a traceback for the error. Could you possibly send me that?

**Comment by mhabiballa** [comment]
@Qwiko 
Ok. Thanks I thought there will be a global topo view. 

> ('layers_sort_order' vs 'icon_model_map' vs 'icon_model_map' vs 'icon_model_map') this is something left to clean up and check if it is needed.
Ok, what I understand that those parameters are no longer needed!. Am I write?

About the logs, here they are:

`2022-12-14 13:54:56,432 django.request ERROR: Internal Server Error: /plugins/nextbox-ui/topology/
Traceback (most recent call last):
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/nextbox_ui_plugin/views.py", line 426, in get
    topology_dict, device_roles, multi_cable_connections, device_tags = get_topology(self.queryset)
  File "/opt/netbox-3.3.9/venv/lib/python3.10/site-packages/nextbox_ui_plugin/views.py", line 300, in get_topology
    if (isinstance(link.a_terminations[0], PowerFeed) or (isinstance(link.b_terminations[0], PowerFeed))):
IndexError: list index out of range
2022-12-14 13:54:56,631 django.request WARNING: Not Found: /favicon.ico`

**Comment by Qwiko** [comment]
@mhabiballa 
I know what this could be caused by.
After the holidays I will look into developing this plugin further and fix bugs. If you have any feature-suggestions please let me know.
